# generated by datamodel-codegen:
#   filename:  openapi-2026-05-01.json
#   timestamp: 2026-05-01T18:34:54+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, confloat, conint, constr


class HikedPoint(BaseModel):
    id: int = Field(
        ...,
        description='Unique identifier for the hiking location',
        examples=[1],
        title='Id',
    )
    park_code: constr(pattern=r'^[a-z]{4}$') = Field(
        ...,
        description='4-character lowercase park code',
        examples=['yose'],
        title='Park Code',
    )
    park_name: str | None = Field(
        None, description='Short park name', examples=['Yosemite'], title='Park Name'
    )
    location_name: str = Field(
        ...,
        description='Name of the hiking location',
        examples=['Vernal Fall'],
        title='Location Name',
    )
    latitude: confloat(ge=-90.0, le=90.0) | None = Field(
        None, description='Latitude coordinate', examples=[37.7268], title='Latitude'
    )
    longitude: confloat(ge=-180.0, le=180.0) | None = Field(
        None,
        description='Longitude coordinate',
        examples=[-119.5428],
        title='Longitude',
    )
    matched_trail_name: str | None = Field(
        None,
        description='Name of the matched trail (if matched)',
        examples=['Mist Trail'],
        title='Matched Trail Name',
    )
    source: str | None = Field(
        None,
        description="Data source of the matched trail ('TNM' or 'OSM')",
        examples=['TNM'],
        title='Source',
    )


class HikedPointsResponse(BaseModel):
    count: conint(ge=0) = Field(
        ...,
        description='Number of hiked points returned',
        examples=[299],
        title='Count',
    )
    hiked_points: list[HikedPoint] = Field(
        ..., description='List of hiked location points', title='Hiked Points'
    )



class PaginationMetadata(BaseModel):
    limit: conint(ge=1, le=1000) = Field(
        ..., description='Number of items per page', examples=[50], title='Limit'
    )
    offset: conint(ge=0) = Field(
        ...,
        description='Number of items skipped (starting position)',
        examples=[0],
        title='Offset',
    )
    total_count: conint(ge=0) = Field(
        ...,
        description='Total number of items matching the query',
        examples=[347],
        title='Total Count',
    )
    has_next: bool = Field(
        ...,
        description='Whether there are more pages after this one',
        examples=[True],
        title='Has Next',
    )
    has_prev: bool = Field(
        ...,
        description='Whether there are previous pages before this one',
        examples=[False],
        title='Has Prev',
    )


class Park(BaseModel):
    park_code: constr(pattern=r'^[a-z]{4}$') = Field(
        ...,
        description='4-character lowercase park code',
        examples=['yose'],
        title='Park Code',
    )
    park_name: str | None = Field(
        None, description='Short park name', examples=['Yosemite'], title='Park Name'
    )
    full_name: str | None = Field(
        None,
        description='Official full name of the park',
        examples=['Yosemite National Park'],
        title='Full Name',
    )
    states: str | None = Field(
        None,
        description='States where the park is located',
        examples=['CA'],
        title='States',
    )
    latitude: confloat(ge=-90.0, le=90.0) | None = Field(
        None, description='Latitude coordinate', examples=[37.8651], title='Latitude'
    )
    longitude: confloat(ge=-180.0, le=180.0) | None = Field(
        None,
        description='Longitude coordinate',
        examples=[-119.5383],
        title='Longitude',
    )
    url: str | None = Field(
        None,
        description='NPS website URL for the park',
        examples=['https://www.nps.gov/yose/index.htm'],
        title='Url',
    )
    designation: str | None = Field(
        None,
        description="NPS designation (e.g., 'National Park', 'National Park & Preserve')",
        examples=['National Park'],
        title='Designation',
    )
    visit_month: str | None = Field(
        None, description='Month of park visit', examples=['July'], title='Visit Month'
    )
    visit_year: int | None = Field(
        None, description='Year of park visit', examples=[2023], title='Visit Year'
    )
    description: str | None = Field(
        None,
        description='Park description (only included when description=true)',
        examples=[
            'Not just a great valley, but a shrine to human foresight, the strength of granite...'
        ],
        title='Description',
    )
    boundary: dict[str, Any] | None = Field(
        None,
        description='Simplified park boundary as GeoJSON geometry (only included when boundary=true)',
        title='Boundary',
    )


class ParkStats(BaseModel):
    park_code: constr(pattern=r'^[a-z]{4}$') = Field(
        ...,
        description='4-character lowercase park code',
        examples=['yose'],
        title='Park Code',
    )
    park_name: str | None = Field(
        None, description='Short park name', examples=['Yosemite'], title='Park Name'
    )
    trail_count: conint(ge=0) = Field(
        ...,
        description='Number of trails in this park',
        examples=[42],
        title='Trail Count',
    )
    total_miles: confloat(ge=0.0) = Field(
        ...,
        description='Total trail mileage in this park',
        examples=[187.3],
        title='Total Miles',
    )
    avg_trail_length: confloat(ge=0.0) = Field(
        ...,
        description='Average trail length in this park',
        examples=[4.46],
        title='Avg Trail Length',
    )


class ParkStatsResponse(BaseModel):
    park_count: conint(ge=0) = Field(
        ...,
        description='Number of parks with trails',
        examples=[36],
        title='Park Count',
    )
    parks: list[ParkStats] = Field(
        ...,
        description='Per-park statistics sorted by trail count descending',
        title='Parks',
    )


class ParksResponse(BaseModel):
    park_count: conint(ge=0) = Field(
        ...,
        description='Total number of parks returned',
        examples=[63],
        title='Park Count',
    )
    visited_count: conint(ge=0) = Field(
        ...,
        description='Number of parks that have been visited',
        examples=[36],
        title='Visited Count',
    )
    parks: list[Park] = Field(..., description='List of parks', title='Parks')


class SourceBreakdown(BaseModel):
    tnm: conint(ge=0) = Field(
        ...,
        description='Number of trails from The National Map',
        examples=[200],
        title='Tnm',
    )
    osm: conint(ge=0) = Field(
        ...,
        description='Number of trails from OpenStreetMap',
        examples=[147],
        title='Osm',
    )


class Trail(BaseModel):
    trail_id: str = Field(
        ...,
        description='Unique trail identifier (permanent_identifier for TNM, osm_id for OSM)',
        examples=['550779'],
        title='Trail Id',
    )
    trail_name: str | None = Field(
        None,
        description='Trail name (may be null for unnamed trails)',
        examples=['Mono Pass Trail'],
        title='Trail Name',
    )
    park_code: constr(pattern=r'^[a-z]{4}$') = Field(
        ...,
        description='4-character lowercase park code',
        examples=['yose'],
        title='Park Code',
    )
    park_name: str | None = Field(
        None, description='Short park name', examples=['Yosemite'], title='Park Name'
    )
    states: str | None = Field(
        None,
        description='States where parent park is located (approximate - trail may not span all states)',
        examples=['CA'],
        title='States',
    )
    source: str = Field(
        ..., description='Data source (TNM or OSM)', examples=['TNM'], title='Source'
    )
    length_miles: confloat(ge=0.0) = Field(
        ..., description='Trail length in miles', examples=[8.2], title='Length Miles'
    )
    geometry_type: str = Field(
        ...,
        description='Geometry type (LineString or MultiLineString)',
        examples=['LineString'],
        title='Geometry Type',
    )
    highway_type: str | None = Field(
        None,
        description='OSM highway tag (path, footway, track, etc.) - only available for OSM trails',
        examples=['path'],
        title='Highway Type',
    )
    hiked: bool = Field(
        ...,
        description='Whether this trail has been hiked',
        examples=[True],
        title='Hiked',
    )
    viz_3d_available: bool = Field(
        ...,
        description='Whether 3D visualization is available for this trail (requires elevation data)',
        examples=[True],
        title='Viz 3D Available',
    )
    viz_3d_slug: str | None = Field(
        None,
        description='URL-safe trail slug for 3D visualization endpoint (only present if viz_3d_available is true)',
        examples=['mono_pass_trail'],
        title='Viz 3D Slug',
    )
    geometry: dict[str, Any] | None = Field(
        None,
        description='Trail geometry as GeoJSON (only included when geojson=true)',
        title='Geometry',
    )


class TrailSummary(BaseModel):
    trail_name: str | None = Field(
        None, description='Trail name', examples=['Half Dome Trail'], title='Trail Name'
    )
    park_code: constr(pattern=r'^[a-z]{4}$') = Field(
        ...,
        description='4-character lowercase park code',
        examples=['yose'],
        title='Park Code',
    )
    park_name: str | None = Field(
        None, description='Short park name', examples=['Yosemite'], title='Park Name'
    )
    length_miles: confloat(ge=0.0) = Field(
        ..., description='Trail length in miles', examples=[14.2], title='Length Miles'
    )


class TrailsResponse(BaseModel):
    trail_count: conint(ge=0) = Field(
        ...,
        description='Number of trails returned in this page',
        examples=[50],
        title='Trail Count',
    )
    total_miles: confloat(ge=0.0) = Field(
        ...,
        description='Total trail mileage for trails in this page',
        examples=[342.7],
        title='Total Miles',
    )
    trails: list[Trail] = Field(
        ..., description='List of trails matching the query', title='Trails'
    )
    pagination: PaginationMetadata = Field(
        ...,
        description='Pagination metadata including total count and navigation flags',
    )



class ParkSummaryResponse(BaseModel):
    park_code: constr(pattern=r'^[a-z]{4}$') = Field(
        ...,
        description='4-character lowercase park code',
        examples=['yose'],
        title='Park Code',
    )
    park_name: str | None = Field(
        None, description='Short park name', examples=['Yosemite'], title='Park Name'
    )
    full_name: str | None = Field(
        None,
        description='Official full name of the park',
        examples=['Yosemite National Park'],
        title='Full Name',
    )
    designation: str | None = Field(
        None,
        description='NPS designation',
        examples=['National Park'],
        title='Designation',
    )
    states: str | None = Field(
        None,
        description='States where the park is located',
        examples=['CA'],
        title='States',
    )
    latitude: confloat(ge=-90.0, le=90.0) | None = Field(
        None, description='Latitude coordinate', examples=[37.8651], title='Latitude'
    )
    longitude: confloat(ge=-180.0, le=180.0) | None = Field(
        None,
        description='Longitude coordinate',
        examples=[-119.5383],
        title='Longitude',
    )
    url: str | None = Field(
        None,
        description='NPS website URL for the park',
        examples=['https://www.nps.gov/yose/index.htm'],
        title='Url',
    )
    visit_month: str | None = Field(
        None, description='Month of park visit', examples=['July'], title='Visit Month'
    )
    visit_year: int | None = Field(
        None, description='Year of park visit', examples=[2023], title='Visit Year'
    )
    total_trails: conint(ge=0) = Field(
        ...,
        description='Total number of deduplicated trails in this park',
        examples=[42],
        title='Total Trails',
    )
    total_miles: confloat(ge=0.0) = Field(
        ...,
        description='Total trail mileage in this park',
        examples=[187.3],
        title='Total Miles',
    )
    avg_trail_length: confloat(ge=0.0) = Field(
        ...,
        description='Average trail length in miles',
        examples=[4.46],
        title='Avg Trail Length',
    )
    hiked_trails: conint(ge=0) = Field(
        ...,
        description='Number of trails hiked in this park',
        examples=[15],
        title='Hiked Trails',
    )
    hiked_miles: confloat(ge=0.0) = Field(
        ...,
        description='Total miles of hiked trails in this park',
        examples=[67.2],
        title='Hiked Miles',
    )
    source_breakdown: SourceBreakdown = Field(
        ..., description='Trail counts by data source (TNM vs OSM)'
    )
    viz_3d_count: conint(ge=0) = Field(
        ...,
        description='Number of trails with 3D visualization available',
        examples=[10],
        title='Viz 3D Count',
    )


class StatsResponse(BaseModel):
    total_trails: conint(ge=0) = Field(
        ...,
        description='Total number of deduplicated trails',
        examples=[347],
        title='Total Trails',
    )
    total_miles: confloat(ge=0.0) = Field(
        ..., description='Total trail mileage', examples=[1523.4], title='Total Miles'
    )
    avg_trail_length: confloat(ge=0.0) = Field(
        ...,
        description='Average trail length in miles',
        examples=[4.39],
        title='Avg Trail Length',
    )
    parks_count: conint(ge=0) = Field(
        ...,
        description='Number of distinct parks with trails',
        examples=[36],
        title='Parks Count',
    )
    states_count: conint(ge=0) = Field(
        ...,
        description='Number of distinct states covered',
        examples=[22],
        title='States Count',
    )
    source_breakdown: SourceBreakdown = Field(
        ..., description='Trail counts by data source (TNM vs OSM)'
    )
    longest_trail: TrailSummary | None = Field(
        None, description='The longest trail matching the filters'
    )
    shortest_trail: TrailSummary | None = Field(
        None, description='The shortest trail matching the filters'
    )
