# generated by datamodel-codegen:
#   filename:  openapi-2026-07-06.json
#   timestamp: 2026-07-06T12:54:09+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field


class HikedPoint(BaseModel):
    id: Annotated[
        int,
        Field(
            description='Unique identifier for the hiking location',
            examples=[1],
            title='Id',
        ),
    ]
    park_code: Annotated[
        str,
        Field(
            description='4-character lowercase park code',
            examples=['yose'],
            pattern='^[a-z]{4}$',
            title='Park Code',
        ),
    ]
    park_name: Annotated[
        str | None,
        Field(description='Short park name', examples=['Yosemite'], title='Park Name'),
    ] = None
    location_name: Annotated[
        str,
        Field(
            description='Name of the hiking location',
            examples=['Vernal Fall'],
            title='Location Name',
        ),
    ]
    latitude: Annotated[
        float | None,
        Field(description='Latitude coordinate', examples=[37.7268], ge=-90.0, le=90.0, title='Latitude'),
    ] = None
    longitude: Annotated[
        float | None,
        Field(
            description='Longitude coordinate', examples=[-119.5428], ge=-180.0, le=180.0, title='Longitude'
        ),
    ] = None
    matched_trail_name: Annotated[
        str | None,
        Field(
            description='Name of the matched trail (if matched)',
            examples=['Mist Trail'],
            title='Matched Trail Name',
        ),
    ] = None
    source: Annotated[
        str | None,
        Field(
            description="Data source of the matched trail ('TNM' or 'OSM')",
            examples=['TNM'],
            title='Source',
        ),
    ] = None


class HikedPointsResponse(BaseModel):
    count: Annotated[
        int,
        Field(
            description='Number of hiked points returned',
            examples=[299],
            ge=0,
            title='Count',
        ),
    ]
    hiked_points: Annotated[
        list[HikedPoint],
        Field(description='List of hiked location points', title='Hiked Points'),
    ]


class PaginationMetadata(BaseModel):
    limit: Annotated[
        int,
        Field(
            description='Number of items per page',
            examples=[50],
            ge=1,
            le=1000,
            title='Limit',
        ),
    ]
    offset: Annotated[
        int,
        Field(
            description='Number of items skipped (starting position)',
            examples=[0],
            ge=0,
            title='Offset',
        ),
    ]
    total_count: Annotated[
        int,
        Field(
            description='Total number of items matching the query',
            examples=[347],
            ge=0,
            title='Total Count',
        ),
    ]
    has_next: Annotated[
        bool,
        Field(
            description='Whether there are more pages after this one',
            examples=[True],
            title='Has Next',
        ),
    ]
    has_prev: Annotated[
        bool,
        Field(
            description='Whether there are previous pages before this one',
            examples=[False],
            title='Has Prev',
        ),
    ]


class Park(BaseModel):
    park_code: Annotated[
        str,
        Field(
            description='4-character lowercase park code',
            examples=['yose'],
            pattern='^[a-z]{4}$',
            title='Park Code',
        ),
    ]
    park_name: Annotated[
        str | None,
        Field(description='Short park name', examples=['Yosemite'], title='Park Name'),
    ] = None
    full_name: Annotated[
        str | None,
        Field(
            description='Official full name of the park',
            examples=['Yosemite National Park'],
            title='Full Name',
        ),
    ] = None
    states: Annotated[
        str | None,
        Field(
            description='States where the park is located',
            examples=['CA'],
            title='States',
        ),
    ] = None
    latitude: Annotated[
        float | None,
        Field(description='Latitude coordinate', examples=[37.8651], ge=-90.0, le=90.0, title='Latitude'),
    ] = None
    longitude: Annotated[
        float | None,
        Field(
            description='Longitude coordinate', examples=[-119.5383], ge=-180.0, le=180.0, title='Longitude'
        ),
    ] = None
    url: Annotated[
        str | None,
        Field(
            description='NPS website URL for the park',
            examples=['https://www.nps.gov/yose/index.htm'],
            title='Url',
        ),
    ] = None
    designation: Annotated[
        str | None,
        Field(
            description="NPS designation (e.g., 'National Park', 'National Park & Preserve')",
            examples=['National Park'],
            title='Designation',
        ),
    ] = None
    visit_month: Annotated[
        str | None,
        Field(
            description='Month of park visit', examples=['July'], title='Visit Month'
        ),
    ] = None
    visit_year: Annotated[
        int | None,
        Field(description='Year of park visit', examples=[2023], title='Visit Year'),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description='Park description (only included when description=true)',
            examples=[
                'Not just a great valley, but a shrine to human foresight, the strength of granite...'
            ],
            title='Description',
        ),
    ] = None
    boundary: Annotated[
        dict[str, Any] | None,
        Field(
            description='Simplified park boundary as GeoJSON geometry (only included when boundary=true)',
            title='Boundary',
        ),
    ] = None


class ParkStats(BaseModel):
    park_code: Annotated[
        str,
        Field(
            description='4-character lowercase park code',
            examples=['yose'],
            pattern='^[a-z]{4}$',
            title='Park Code',
        ),
    ]
    park_name: Annotated[
        str | None,
        Field(description='Short park name', examples=['Yosemite'], title='Park Name'),
    ] = None
    trail_count: Annotated[
        int,
        Field(
            description='Number of trails in this park',
            examples=[42],
            ge=0,
            title='Trail Count',
        ),
    ]
    total_miles: Annotated[
        float,
        Field(
            description='Total trail mileage in this park',
            examples=[187.3],
            ge=0.0,
            title='Total Miles',
        ),
    ]
    avg_trail_length: Annotated[
        float,
        Field(
            description='Average trail length in this park',
            examples=[4.46],
            ge=0.0,
            title='Avg Trail Length',
        ),
    ]


class ParkStatsResponse(BaseModel):
    park_count: Annotated[
        int,
        Field(
            description='Number of parks with trails',
            examples=[36],
            ge=0,
            title='Park Count',
        ),
    ]
    parks: Annotated[
        list[ParkStats],
        Field(
            description='Per-park statistics sorted by trail count descending',
            title='Parks',
        ),
    ]


class ParksResponse(BaseModel):
    park_count: Annotated[
        int,
        Field(
            description='Total number of parks returned',
            examples=[63],
            ge=0,
            title='Park Count',
        ),
    ]
    visited_count: Annotated[
        int,
        Field(
            description='Number of parks that have been visited',
            examples=[36],
            ge=0,
            title='Visited Count',
        ),
    ]
    parks: Annotated[list[Park], Field(description='List of parks', title='Parks')]


class SourceBreakdown(BaseModel):
    tnm: Annotated[
        int,
        Field(
            description='Number of trails from The National Map',
            examples=[200],
            ge=0,
            title='Tnm',
        ),
    ]
    osm: Annotated[
        int,
        Field(
            description='Number of trails from OpenStreetMap',
            examples=[147],
            ge=0,
            title='Osm',
        ),
    ]


class Trail(BaseModel):
    trail_id: Annotated[
        str,
        Field(
            description='Unique trail identifier (permanent_identifier for TNM, osm_id for OSM)',
            examples=['550779'],
            title='Trail Id',
        ),
    ]
    trail_name: Annotated[
        str | None,
        Field(
            description='Trail name (may be null for unnamed trails)',
            examples=['Mono Pass Trail'],
            title='Trail Name',
        ),
    ] = None
    park_code: Annotated[
        str,
        Field(
            description='4-character lowercase park code',
            examples=['yose'],
            pattern='^[a-z]{4}$',
            title='Park Code',
        ),
    ]
    park_name: Annotated[
        str | None,
        Field(description='Short park name', examples=['Yosemite'], title='Park Name'),
    ] = None
    states: Annotated[
        str | None,
        Field(
            description='States where parent park is located (approximate - trail may not span all states)',
            examples=['CA'],
            title='States',
        ),
    ] = None
    source: Annotated[
        str,
        Field(description='Data source (TNM or OSM)', examples=['TNM'], title='Source'),
    ]
    length_miles: Annotated[
        float,
        Field(
            description='Trail length in miles',
            examples=[8.2],
            ge=0.0,
            title='Length Miles',
        ),
    ]
    geometry_type: Annotated[
        str,
        Field(
            description='Geometry type (LineString or MultiLineString)',
            examples=['LineString'],
            title='Geometry Type',
        ),
    ]
    highway_type: Annotated[
        str | None,
        Field(
            description='OSM highway tag (path, footway, track, etc.) - only available for OSM trails',
            examples=['path'],
            title='Highway Type',
        ),
    ] = None
    hiked: Annotated[
        bool,
        Field(
            description='Whether this trail has been hiked',
            examples=[True],
            title='Hiked',
        ),
    ]
    viz_3d_available: Annotated[
        bool,
        Field(
            description='Whether 3D visualization is available for this trail (requires elevation data)',
            examples=[True],
            title='Viz 3D Available',
        ),
    ]
    viz_3d_slug: Annotated[
        str | None,
        Field(
            description='URL-safe trail slug for 3D visualization endpoint (only present if viz_3d_available is true)',
            examples=['mono_pass_trail'],
            title='Viz 3D Slug',
        ),
    ] = None
    geometry: Annotated[
        dict[str, Any] | None,
        Field(
            description='Trail geometry as GeoJSON (only included when geojson=true)',
            title='Geometry',
        ),
    ] = None


class TrailSummary(BaseModel):
    trail_name: Annotated[
        str | None,
        Field(
            description='Trail name', examples=['Half Dome Trail'], title='Trail Name'
        ),
    ] = None
    park_code: Annotated[
        str,
        Field(
            description='4-character lowercase park code',
            examples=['yose'],
            pattern='^[a-z]{4}$',
            title='Park Code',
        ),
    ]
    park_name: Annotated[
        str | None,
        Field(description='Short park name', examples=['Yosemite'], title='Park Name'),
    ] = None
    length_miles: Annotated[
        float,
        Field(
            description='Trail length in miles',
            examples=[14.2],
            ge=0.0,
            title='Length Miles',
        ),
    ]


class TrailsResponse(BaseModel):
    trail_count: Annotated[
        int,
        Field(
            description='Number of trails returned in this page',
            examples=[50],
            ge=0,
            title='Trail Count',
        ),
    ]
    total_miles: Annotated[
        float,
        Field(
            description='Total trail mileage for trails in this page',
            examples=[342.7],
            ge=0.0,
            title='Total Miles',
        ),
    ]
    trails: Annotated[
        list[Trail],
        Field(description='List of trails matching the query', title='Trails'),
    ]
    pagination: Annotated[
        PaginationMetadata,
        Field(
            description='Pagination metadata including total count and navigation flags'
        ),
    ]


class ParkSummaryResponse(BaseModel):
    park_code: Annotated[
        str,
        Field(
            description='4-character lowercase park code',
            examples=['yose'],
            pattern='^[a-z]{4}$',
            title='Park Code',
        ),
    ]
    park_name: Annotated[
        str | None,
        Field(description='Short park name', examples=['Yosemite'], title='Park Name'),
    ] = None
    full_name: Annotated[
        str | None,
        Field(
            description='Official full name of the park',
            examples=['Yosemite National Park'],
            title='Full Name',
        ),
    ] = None
    designation: Annotated[
        str | None,
        Field(
            description='NPS designation',
            examples=['National Park'],
            title='Designation',
        ),
    ] = None
    states: Annotated[
        str | None,
        Field(
            description='States where the park is located',
            examples=['CA'],
            title='States',
        ),
    ] = None
    latitude: Annotated[
        float | None,
        Field(description='Latitude coordinate', examples=[37.8651], ge=-90.0, le=90.0, title='Latitude'),
    ] = None
    longitude: Annotated[
        float | None,
        Field(
            description='Longitude coordinate', examples=[-119.5383], ge=-180.0, le=180.0, title='Longitude'
        ),
    ] = None
    url: Annotated[
        str | None,
        Field(
            description='NPS website URL for the park',
            examples=['https://www.nps.gov/yose/index.htm'],
            title='Url',
        ),
    ] = None
    visit_month: Annotated[
        str | None,
        Field(
            description='Month of park visit', examples=['July'], title='Visit Month'
        ),
    ] = None
    visit_year: Annotated[
        int | None,
        Field(description='Year of park visit', examples=[2023], title='Visit Year'),
    ] = None
    total_trails: Annotated[
        int,
        Field(
            description='Total number of deduplicated trails in this park',
            examples=[42],
            ge=0,
            title='Total Trails',
        ),
    ]
    total_miles: Annotated[
        float,
        Field(
            description='Total trail mileage in this park',
            examples=[187.3],
            ge=0.0,
            title='Total Miles',
        ),
    ]
    avg_trail_length: Annotated[
        float,
        Field(
            description='Average trail length in miles',
            examples=[4.46],
            ge=0.0,
            title='Avg Trail Length',
        ),
    ]
    hiked_trails: Annotated[
        int,
        Field(
            description='Number of trails hiked in this park',
            examples=[15],
            ge=0,
            title='Hiked Trails',
        ),
    ]
    hiked_miles: Annotated[
        float,
        Field(
            description='Total miles of hiked trails in this park',
            examples=[67.2],
            ge=0.0,
            title='Hiked Miles',
        ),
    ]
    source_breakdown: Annotated[
        SourceBreakdown, Field(description='Trail counts by data source (TNM vs OSM)')
    ]
    viz_3d_count: Annotated[
        int,
        Field(
            description='Number of trails with 3D visualization available',
            examples=[10],
            ge=0,
            title='Viz 3D Count',
        ),
    ]


class StatsResponse(BaseModel):
    total_trails: Annotated[
        int,
        Field(
            description='Total number of deduplicated trails',
            examples=[347],
            ge=0,
            title='Total Trails',
        ),
    ]
    total_miles: Annotated[
        float,
        Field(
            description='Total trail mileage',
            examples=[1523.4],
            ge=0.0,
            title='Total Miles',
        ),
    ]
    avg_trail_length: Annotated[
        float,
        Field(
            description='Average trail length in miles',
            examples=[4.39],
            ge=0.0,
            title='Avg Trail Length',
        ),
    ]
    parks_count: Annotated[
        int,
        Field(
            description='Number of distinct parks with trails',
            examples=[36],
            ge=0,
            title='Parks Count',
        ),
    ]
    states_count: Annotated[
        int,
        Field(
            description='Number of distinct states covered',
            examples=[22],
            ge=0,
            title='States Count',
        ),
    ]
    source_breakdown: Annotated[
        SourceBreakdown, Field(description='Trail counts by data source (TNM vs OSM)')
    ]
    longest_trail: Annotated[
        TrailSummary | None, Field(description='The longest trail matching the filters')
    ] = None
    shortest_trail: Annotated[
        TrailSummary | None,
        Field(description='The shortest trail matching the filters'),
    ] = None
